### ISSUE TITLE
AppVeyor upload issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/versioneer-feedstock#1]
Was having some issues uploading packages on AppVeyor specifically. See issue ( https://github.com/conda-forge/status/issues/4 ) for details. Example of the failure can be seen in this [build](https://ci.appveyor.com/project/conda-forge/versioneer-feedstock/build/1.0.1/job/ti9honaau2d596yf#L330). Doesn't appear to be any reason as to which builds fail or if they do ATM. Traceback of the error shown below.

```
python ci_support\upload_or_check_non_existence.py .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "ci_support\upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "ci_support\upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "ci_support\upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "C:\conda\lib\site-packages\binstar_client\mixins\channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "C:\conda\lib\site-packages\binstar_client\__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: (u'Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
Command exited with code 1
```

**Comment by jakirkham** [comment]
It appears that after a couple of restarts the CI [build](https://ci.appveyor.com/project/conda-forge/versioneer-feedstock/build/1.0.3) passed and the remaining packages have been uploaded. Still not sure what the cause was or if it is resolved.
